---
# tasks file for roles/bootcamp2
- name: Find out stuff
  hosts: all
  connection: local
  tasks:
  - name: Find the hostname
    setup:
     filter: "*hostname*"
  - name: Find the hostname
    debug:
     var: ansible_hostname
  - name: Find the IPv4 address
    debug: var=ansible_default_ipv4.address
  - name: Copy a file
    copy:
     content: "The content of the file"
     dest : "/home/theguy/interfaces"

